# Load imfile module
module(load="imfile")

# Pi-hole DNS query log (dnsmasq)
input(type="imfile"
      File="/root/pihole/logs-pihole/pihole.log"
      Tag="pihole-dnsmasq"
      Facility="local0"
      Severity="info"
)

# Pi-hole FTL daemon log
input(type="imfile"
      File="/root/pihole/logs-pihole/FTL.log"
      Tag="pihole-ftl"
      Facility="local0"
      Severity="info"
)

# Pi-hole Webserver log
input(type="imfile"
      File="/root/pihole/logs-pihole/webserver.log"
      Tag="pihole-webserver"
      Facility="local0"
      Severity="info"
)

# Forward only tagged pihole logs to Logstash over TCP
if $syslogtag contains "pihole" then @@10.50.50.165:5514